(()=>{const API='https://script.google.com/macros/s/AKfycbwf3-MNZBBi64zXcNH7wfhBRoEBl9brtQ9QRI4Won5RmUIOrl_WBivN6uI5NAp6Mc0h/exec';window.API=API;const pages=['overview','upper','lower','west','people','images','presentation','practice'],$=id=>document.getElementById(id),state=JSON.parse(localStorage.getItem('galilee-progress')||'{"done":[]}');let current=Math.max(0,pages.indexOf(location.hash.slice(1)));function save(){localStorage.setItem('galilee-progress',JSON.stringify(state));progress()}function progress(){const n=Math.round(state.done.length/pages.length*100);$('unitPercent').textContent=n+'%';$('unitMeter').style.width=n+'%';document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('done',state.done.includes(b.dataset.page)))}function show(i){current=Math.max(0,Math.min(pages.length-1,i));const id=pages[current];document.querySelectorAll('[data-page-panel]').forEach(p=>p.hidden=p.dataset.pagePanel!==id);document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('pageCounter').textContent='דף '+(current+1)+' מתוך '+pages.length;$('prevPage').disabled=current===0;$('nextPage').disabled=current===pages.length-1;history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{show(pages.indexOf(b.dataset.page));$('unitRail').classList.remove('open')});document.querySelectorAll('.complete-page').forEach(b=>b.onclick=()=>{const id=b.closest('[data-page-panel]').dataset.pagePanel;if(!state.done.includes(id))state.done.push(id);save();if(current<pages.length-1)show(current+1)});$('prevPage').onclick=()=>show(current-1);$('nextPage').onclick=()=>show(current+1);$('menuToggle').onclick=()=>$('unitRail').classList.toggle('open');
const seen=new Set(JSON.parse(localStorage.getItem('galilee-images')||'[]'));document.querySelectorAll('[data-recognition]').forEach(card=>{if(seen.has(card.dataset.recognition))card.classList.add('revealed');card.onclick=()=>{card.classList.add('revealed');seen.add(card.dataset.recognition);localStorage.setItem('galilee-images',JSON.stringify([...seen]))}});
const slides=[['שלושה אזורים','עליון, תחתון ומערבי — לכל אחד נוף ומוצר תיירותי שונה'],['גליל עליון','מים, חורש, עמק החולה, צפת והמושבות'],['גליל תחתון','הארבל, ציפורי, טבריה, נצרת וסובב כנרת'],['גליל מערבי','ראש הנקרה, אכזיב, נחל כזיב ומבצרים'],['עכו','עיר רב־שכבתית: צלבנים, עות׳מאנים ודתות'],['מגוון אנושי','יהדות, נצרות, אסלאם, דרוזים ובהאים'],['מסכמים','טבע + מורשת + אמונה + קהילה = מוצר תיירותי מגוון']];let slide=0;function renderSlide(){const s=slides[slide];$('galileeSlideStage').innerHTML='<article class="region-slide"><div><span>יחידת הגליל</span><h3>'+s[0]+'</h3><p>'+s[1]+'</p></div>'+(s[2]?'<img src="'+s[2]+'" alt="">':'')+'</article>';$('galileeSlideCount').textContent=(slide+1)+' / '+slides.length}$('galileePrevSlide').onclick=()=>{slide=(slide-1+slides.length)%slides.length;renderSlide()};$('galileeNextSlide').onclick=()=>{slide=(slide+1)%slides.length;renderSlide()};$('galileeFullscreen').onclick=()=>document.querySelector('.slide-deck').requestFullscreen?.();renderSlide();
const practice=["ציינו שלושה גורמי משיכה תיירותיים של הגליל, והביאו דוגמה לאחד מהם.","ציינו שני אתרים קדושים ליהודים בעיר טבריה, והסבירו מדוע הם מושכים מאמינים.","ציינו שני גנים לאומיים או שמורות טבע בגליל, ותארו כל אחד מהם.","תארו אירוע אחד בעל משמעות דתית שהתרחש באזור הכנרת על פי המסורת הנוצרית, וציינו אתר המנציח אותו.","ציינו מוזיאון אחד וכנסייה אחת באזור סובב כנרת הקשורים לאירועים בחיי ישו, ותארו את הקשר של אחד מהם לחייו.","ציינו אתר מעיינות חמים בטבריה או בסביבתה המשמש לתיירות מרפא, ותארו ממצא ארכיאולוגי שהתגלה בסמוך אליו."];$('galileePractice').innerHTML='<article class="exam-question"><h3>שאלות בגרות אמיתיות — גליל וסובב כנרת</h3>'+practice.map((q,i)=>'<div class="exam-part"><label><b>'+(i+1)+'.</b> '+q+'</label><textarea data-question="'+q+'" data-key="practice-'+i+'"></textarea><button class="check-exam">בדיקת הסעיף</button><div class="answer-feedback"></div></div>').join('')+'</article>';
async function submit(t,f){const answer=t.value.trim();if(answer.split(/\s+/).length<10){f.textContent='כדאי לכתוב תשובה מלאה ומנומקת יותר.';f.className='answer-feedback needs-work';return}const session=JSON.parse(sessionStorage.getItem('kitahUser')||'null');if(!session?.token){localStorage.setItem('galilee-'+(t.dataset.key||t.dataset.openQuestion),answer);f.textContent='נשמר במכשיר. התחברו כדי לשמור גם למורה.';f.className='answer-feedback local';return}f.textContent='בודק את התשובה…';try{const r=await fetch(window.API,{method:'POST',body:JSON.stringify({action:'submitOpenAnswer',token:session.token,unit_id:'galil',question:t.dataset.question||t.dataset.openQuestion,answer})}),d=await r.json();if(!d.ok)throw new Error(d.error||'שגיאה');f.textContent=d.data?.feedback||'התשובה נשלחה ונשמרה.';f.className='answer-feedback success'}catch(e){f.textContent='הבדיקה אינה זמינה כרגע; התשובה נשמרה במכשיר.';f.className='answer-feedback local';localStorage.setItem('galilee-'+(t.dataset.key||t.dataset.openQuestion),answer)}}document.querySelectorAll('.check-open,.check-exam').forEach(b=>b.onclick=()=>{const box=b.parentElement;submit(box.querySelector('textarea'),box.querySelector('.answer-feedback'))});progress();show(current)})();


/* ===== "המאמן שלי לבגרות" — צ'אט עזרה, עונה אך ורק מתוך חומר הלימוד (askBagrutBot, endpoint פתוח בלי login) ===== */
async function callBagrutBot(question,mode,bagrutQuestion){
  let res,data;try{res=await fetch(window.API,{method:'POST',body:JSON.stringify({action:'askBagrutBot',question,mode:mode||'qa',bagrut_question:bagrutQuestion||''})});data=await res.json();}catch(netErr){throw new Error('אין חיבור לשרת כרגע, נסו שוב בעוד רגע');}
  if(!data.ok)throw new Error(data.error||'שגיאה');
  return data.data.reply;
}
function toggleCoachWidget(open){document.getElementById('coachWidget')?.classList.toggle('open',open)}
function appendCoachMsg(role,text){const log=document.getElementById('coachLog');if(!log)return null;const div=document.createElement('div');div.className='coach-msg coach-msg-'+role;div.textContent=text;log.appendChild(div);log.scrollTop=log.scrollHeight;return div}
async function sendCoachQuestion(e){if(e)e.preventDefault();const input=document.getElementById('coachInput'),q=input.value.trim();if(!q)return;input.value='';appendCoachMsg('user',q);const pending=appendCoachMsg('bot','...חושב, רגע');try{pending.textContent=await callBagrutBot(q,'qa','')}catch(err){pending.textContent='שגיאה: '+err.message}}
