const regionSteps=[...document.querySelectorAll('.lesson-nav [data-step]')].map(x=>x.dataset.step),regionKey='jerusalem',regionUnitId='yerushalayim';
const regionDone=new Set(JSON.parse(localStorage.getItem(regionKey+'-progress')||'[]'));let regionUser=null;try{regionUser=JSON.parse(sessionStorage.getItem('kitahUser')||'null')}catch(_){}
const regionApiUrl='https://script.google.com/macros/s/AKfycbwf3-MNZBBi64zXcNH7wfhBRoEBl9brtQ9QRI4Won5RmUIOrl_WBivN6uI5NAp6Mc0h/exec';
async function regionAPI(action,params={}){if(!regionUser?.token)return null;const r=await fetch(regionApiUrl,{method:'POST',body:JSON.stringify({action,token:regionUser.token,...params})}),d=await r.json();if(!d.ok)throw new Error(d.error||'שגיאה');return d.data}
function renderRegionProgress(){const pct=Math.round(regionDone.size/regionSteps.length*100);document.getElementById('unitPercent').textContent=pct+'%';document.getElementById('unitMeter').style.width=pct+'%';document.querySelectorAll('.lesson-nav [data-step]').forEach(a=>a.classList.toggle('completed',regionDone.has(a.dataset.step)))}
document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>{regionDone.add(b.dataset.complete);localStorage.setItem(regionKey+'-progress',JSON.stringify([...regionDone]));renderRegionProgress();showRegionPage(regionSteps[Math.min(regionSteps.indexOf(b.dataset.complete)+1,regionSteps.length-1)])}));
function showRegionPage(id){document.querySelectorAll('.learning-block').forEach(s=>s.classList.toggle('active-lesson-page',s.id===id));document.querySelectorAll('.lesson-nav [data-step]').forEach(a=>a.classList.toggle('active',a.dataset.step===id));history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.lesson-nav [data-step]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showRegionPage(a.dataset.step)}));
document.getElementById('railButton')?.addEventListener('click',()=>document.getElementById('lessonRail').classList.toggle('open'));
const recognitionSeen=new Set(JSON.parse(localStorage.getItem(regionKey+'-recognition')||'[]'));function renderRecognition(){document.querySelectorAll('[data-recognition-card]').forEach((card,i)=>card.classList.toggle('revealed',recognitionSeen.has(i)));const status=document.getElementById('recognitionProgress');if(status)status.textContent=`${recognitionSeen.size} מתוך 6 אתרים נחשפו`;if(recognitionSeen.size===6){regionDone.add('images');localStorage.setItem(regionKey+'-progress',JSON.stringify([...regionDone]));renderRegionProgress()}}document.querySelectorAll('[data-recognition-card]').forEach((card,i)=>card.addEventListener('click',()=>{recognitionSeen.add(i);localStorage.setItem(regionKey+'-recognition',JSON.stringify([...recognitionSeen]));renderRecognition()}));renderRecognition();
const regionQuestions=[{q:'כמה רבעים יש בעיר העתיקה?',a:['שלושה','ארבעה','חמישה'],correct:1,explain:'העיר העתיקה מחולקת לרובע היהודי, הנוצרי, הארמני והמוסלמי.'},{q:'היכן מסתיימת דרך הייסורים?',a:['בכותל המערבי','בכנסיית הקבר','במוזיאון ישראל'],correct:1,explain:'התחנה האחרונה של המסלול נמצאת בכנסיית הקבר.'},{q:'מה מוצג בהיכל הספר?',a:['מגילות ים המלח','מפת מידבא','אוצרות הכנסייה הארמנית'],correct:0,explain:'היכל הספר במוזיאון ישראל מציג את מגילות ים המלח.'}];let regionQuestion=0,regionScore=0,regionResults=[];
function renderRegionQuestion(){const x=regionQuestions[regionQuestion];document.getElementById('quizKicker').textContent=`שאלה ${regionQuestion+1} מתוך ${regionQuestions.length}`;document.getElementById('questionText').textContent=x.q;document.getElementById('answerList').innerHTML='';x.a.forEach((label,i)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{const ok=i===x.correct;regionResults[regionQuestion]={index:regionQuestion,correct:ok};if(ok)regionScore++;document.querySelectorAll('#answerList button').forEach((n,j)=>{n.disabled=true;if(j===x.correct)n.classList.add('correct')});if(!ok)b.classList.add('wrong');document.getElementById('quizFeedback').textContent=x.explain;document.getElementById('nextQuestion').disabled=false};document.getElementById('answerList').appendChild(b)});document.getElementById('quizFeedback').textContent='';document.getElementById('nextQuestion').disabled=true}
document.getElementById('nextQuestion').onclick=()=>{if(regionQuestion<regionQuestions.length-1){regionQuestion++;renderRegionQuestion();return}document.getElementById('regionQuiz').innerHTML=`<h3>הציון שלך: ${Math.round(regionScore/regionQuestions.length*100)}</h3><p>${regionScore>=2?'עברתם את התרגול ✓':'כדאי לחזור ולנסות שוב.'}</p>`;regionAPI('saveBagrutQuizResult',{unit_id:regionUnitId,score:regionScore,total:regionQuestions.length}).catch(()=>{});regionAPI('updateBagrutMistakes',{unit_id:regionUnitId,results:regionResults}).catch(()=>{});if(regionScore>=2){regionDone.add('practice');localStorage.setItem(regionKey+'-progress',JSON.stringify([...regionDone]));renderRegionProgress()}};
document.getElementById('checkJerusalemOpen').onclick=async()=>{const answer=document.getElementById('jerusalemOpenAnswer').value.trim(),box=document.getElementById('jerusalemOpenFeedback'),terms=[['יהדות',['בית המקדש','הר המוריה','עקדת']],['אסלאם',['מוחמד','עלה','מסע הלילה']],['אתרים',['כותל','כיפת הסלע','אל־אקצא']]],normalized=answer.replace(/[״׳]/g,'').toLowerCase(),checks=terms.map(([label,words])=>({label,met:words.some(w=>normalized.includes(w.replace(/[״׳]/g,'').toLowerCase()))})),passed=answer.split(/\s+/).length>=18&&checks.every(x=>x.met);box.className='smart-feedback '+(passed?'passed':'needs-work');box.innerHTML=`<b>${passed?'תשובה מלאה ✓':'כדאי להשלים את התשובה'}</b><ul>${checks.map(x=>`<li class="${x.met?'met':'missing'}">${x.met?'נמצא':'חסר'}: ${x.label}</li>`).join('')}</ul>`;if(regionUser?.token){const note=document.createElement('small');note.textContent='שומר ובודק בכיתה פלוס…';box.appendChild(note);try{const d=await regionAPI('submitOpenAnswer',{unit_id:regionUnitId,question:'הסבירו מדוע הר הבית קדוש ליהדות ולאסלאם, וציינו אתר מרכזי לכל דת.',answer});note.textContent=d?.feedback?'משוב הבוט: '+d.feedback:'נשמר בכיתה פלוס ✓'}catch(e){note.textContent='השמירה נכשלה: '+e.message}}};
renderRegionProgress();renderRegionQuestion();showRegionPage(location.hash.slice(1)||'overview');

