const attempts=JSON.parse(localStorage.getItem('coastal-open-attempts')||'[]');
const completed=JSON.parse(localStorage.getItem('coastal-demo-progress')||'[]');
const passedParts=new Set(JSON.parse(localStorage.getItem('coastal-bank-open-passed-v2')||'[]').map(String));
const questionNames=['נוף ותיירות בדרום','יפו והעיר הלבנה','ארכאולוגיה, בהאים ותל אביב','מוזיאונים והכפרים הדרוזיים','בית גוברין ומוקדי משיכה','גבולות, ראש הנקרה וחיפה','עכו, טבע ודת בחיפה','חיפה, קיסריה ומושבות','זכרון יעקב וסיור מנהרייה'];
const latest=new Map();attempts.forEach(item=>latest.set(`${item.scope}:${item.id}`,item));
const bankAttempts=[...latest.values()].filter(item=>item.scope==='bank');
const average=bankAttempts.length?Math.round(bankAttempts.reduce((sum,item)=>sum+item.score,0)/bankAttempts.length):0;
const improved=attempts.filter((item,index)=>index>0&&item.scope==='bank'&&attempts.slice(0,index).some(old=>old.scope===item.scope&&old.id===item.id&&item.score>old.score)).length;
document.getElementById('teacherStats').innerHTML=`<article><span>התקדמות ביחידה</span><b>${Math.round(completed.length/10*100)}%</b><small>${completed.length} מתוך 10 דפים הושלמו</small></article><article><span>סעיפי בגרות שעברו</span><b>${passedParts.size}/27</b><small>${bankAttempts.length} סעיפים נבדקו לפחות פעם אחת</small></article><article><span>ממוצע רכיבי תשובה</span><b>${average}%</b><small>לפי הניסיון האחרון בכל סעיף</small></article><article><span>שיפורים לאחר משוב</span><b>${improved}</b><small>ניסיונות שבהם הציון עלה</small></article>`;
const missing=bankAttempts.flatMap(item=>item.missing),counts=missing.reduce((all,label)=>(all[label]=(all[label]||0)+1,all),{}),difficulties=Object.entries(counts).sort((a,b)=>b[1]-a[1]);
document.getElementById('difficultyList').innerHTML=difficulties.length?difficulties.slice(0,6).map(([label,count],index)=>`<div><i>${index+1}</i><span><b>${label}</b><small>חסר ב־${count} תשובות אחרונות</small></span><em style="--difficulty:${Math.min(100,count/Math.max(1,bankAttempts.length)*100)}%"></em></div>`).join(''):'<p class="empty-state">עדיין אין מספיק תשובות שנבדקו כדי לזהות דפוס.</p>';
const topDifficulty=difficulties[0]?.[0];document.getElementById('teacherAction').innerHTML=topDifficulty?`<span class="action-number">01</span><h3>לחזור בקצרה על: ${topDifficulty}</h3><p>פתחו את השיעור בדוגמה מלאה, בקשו מהתלמידים לסמן את רכיבי התשובה, ואז אפשרו ניסיון חוזר בשאלה המתאימה.</p><a class="button button-primary" href="units/coastal-plain.html#open-practice">פתיחת תרגול ממוקד</a>`:`<span class="action-number">01</span><h3>לאסוף ניסיון ראשון</h3><p>בקשו מהתלמידים לענות על סעיף אחד לפחות. לאחר הבדיקה תופיע כאן המלצה המבוססת על הקושי החוזר.</p><a class="button button-primary" href="units/coastal-plain.html#open-practice">פתיחת מאגר השאלות</a>`;
document.getElementById('questionPerformance').innerHTML=questionNames.map((name,i)=>{const parts=[0,1,2].map(p=>`${i}-${p}`),passed=parts.filter(key=>passedParts.has(key)).length,questionAttempts=bankAttempts.filter(item=>item.id.startsWith(`${i}-`)),score=questionAttempts.length?Math.round(questionAttempts.reduce((sum,item)=>sum+item.score,0)/questionAttempts.length):0;return`<div><span><b>שאלה ${i+1}</b><small>${name}</small></span><div class="part-dots">${parts.map((key,p)=>`<i class="${passedParts.has(key)?'done':''}" title="סעיף ${String.fromCharCode(1488+p)}">${String.fromCharCode(1488+p)}</i>`).join('')}</div><strong>${passed}/3</strong><em>${questionAttempts.length?score+'%':'טרם נבדק'}</em></div>`}).join('');

const TEACHER_API='https://script.google.com/macros/s/AKfycbwf3-MNZBBi64zXcNH7wfhBRoEBl9brtQ9QRI4Won5RmUIOrl_WBivN6uI5NAp6Mc0h/exec';
let teacherUser=null,roster=[];
try{teacherUser=JSON.parse(sessionStorage.getItem('kitahUser')||'null')}catch(_){}
if(teacherUser)document.getElementById('teacherUserName').textContent=teacherUser.name||teacherUser.email||'מורה';
function switchTeacherTab(id){document.querySelectorAll('[data-teacher-tab]').forEach(x=>x.classList.toggle('active',x.dataset.teacherTab===id));document.querySelectorAll('[data-teacher-tab-button]').forEach(x=>x.classList.toggle('active',x.dataset.teacherTabButton===id))}
document.querySelectorAll('[data-teacher-tab-button]').forEach(b=>b.addEventListener('click',()=>switchTeacherTab(b.dataset.teacherTabButton)));
document.querySelectorAll('[data-open-teacher-tab]').forEach(b=>b.addEventListener('click',()=>switchTeacherTab(b.dataset.openTeacherTab)));
async function teacherAPI(action,params={}){const response=await fetch(TEACHER_API,{method:'POST',body:JSON.stringify({action,token:teacherUser?.token,...params})}),data=await response.json();if(!data.ok)throw new Error(data.error||'שגיאה בחיבור');return data.data}
function renderRoster(){const body=document.getElementById('studentsBody');document.getElementById('rosterSummary').innerHTML=`<b>${roster.length}</b><span>תלמידים רשומים במקצוע</span>`;body.innerHTML=roster.length?roster.map(s=>`<tr><td><b>${s.name||'ללא שם'}</b><small>${s.email||''}</small></td><td>${s.class_name||'—'}</td><td>${s.progress_percent??s.percent??0}%</td><td>${s.best_score??'—'}</td><td>${s.last_active?new Date(s.last_active).toLocaleDateString('he-IL'):'טרם התחיל/ה'}</td><td><button class="table-action" data-student-answers="${s.email}">תשובות</button></td></tr>`).join(''):'<tr><td colspan="6">אין תלמידים רשומים עדיין.</td></tr>';document.querySelectorAll('[data-student-answers]').forEach(b=>b.addEventListener('click',()=>openStudentAnswers(b.dataset.studentAnswers)))}
async function loadClassroom(){if(!teacherUser?.token){document.getElementById('teacherDataState').textContent='נדרשת כניסה מחדש';document.getElementById('overviewMessage').textContent='כדי לטעון את נתוני הכיתה יש להיכנס דרך כיתה פלוס.';document.getElementById('studentsBody').innerHTML='<tr><td colspan="6">נתוני התלמידים יוצגו לאחר כניסה דרך כיתה פלוס.</td></tr>';return}try{const data=await teacherAPI('getBagrutTeacherDashboard');roster=data.students||[];renderRoster();document.getElementById('teacherDataState').textContent='מחובר לכיתה פלוס';document.getElementById('overviewMessage').textContent=roster.length?`${roster.length} תלמידים רשומים. עברו לרשימה כדי לזהות מי טרם התחיל ומי זקוק לחיזוק.`:'עדיין אין תלמידים רשומים במקצוע.'}catch(e){document.getElementById('teacherDataState').textContent='החיבור דורש בדיקה';document.getElementById('overviewMessage').textContent='לא הצלחנו לטעון את נתוני הכיתה: '+e.message;document.getElementById('studentsBody').innerHTML='<tr><td colspan="6">'+e.message+'</td></tr>'}}
document.getElementById('toggleStudentForm').addEventListener('click',()=>document.getElementById('studentAddForm').hidden=!document.getElementById('studentAddForm').hidden);
document.getElementById('studentAddForm').addEventListener('submit',async e=>{e.preventDefault();const feedback=document.getElementById('studentFormFeedback');feedback.textContent='שומר…';try{await teacherAPI('addBagrutStudent',{name:document.getElementById('newStudentName').value.trim(),email:document.getElementById('newStudentEmail').value.trim(),class_name:document.getElementById('newStudentClass').value.trim()});e.target.reset();feedback.textContent='התלמיד/ה נוספו';await loadClassroom()}catch(err){feedback.textContent='שגיאה: '+err.message}});
async function openStudentAnswers(email){switchTeacherTab('answers');const state=document.getElementById('answersState');state.textContent='טוען תשובות…';try{const data=await teacherAPI('getBagrutStudentOpenAnswers',{studentEmail:email}),answers=data.answers||data||[];state.innerHTML=answers.length?answers.map(a=>`<article class="student-answer-card"><span>${a.unit_name||a.unit_id||'יחידה'}</span><h3>${a.question||'שאלה פתוחה'}</h3><p>${a.answer||a.answer_text||''}</p><small>${a.created_at?new Date(a.created_at).toLocaleString('he-IL'):''}</small></article>`).join(''):'אין עדיין תשובות פתוחות לתלמיד/ה זה.'}catch(e){state.textContent='שגיאה: '+e.message}}
loadClassroom();

