const attempts=JSON.parse(localStorage.getItem('coastal-open-attempts')||'[]');
const completed=JSON.parse(localStorage.getItem('coastal-demo-progress')||'[]');
const passedParts=new Set(JSON.parse(localStorage.getItem('coastal-bank-open-passed-v2')||'[]').map(String));
const questionNames=['נוף ותיירות בדרום','יפו והעיר הלבנה','ארכאולוגיה, בהאים ותל אביב','מוזיאונים והכפרים הדרוזיים','בית גוברין ומוקדי משיכה','גבולות, ראש הנקרה וחיפה','עכו, טבע ודת בחיפה','חיפה, קיסריה ומושבות','זכרון יעקב וסיור מנהרייה'];
const latest=new Map();attempts.forEach(item=>latest.set(`${item.scope}:${item.id}`,item));
const bankAttempts=[...latest.values()].filter(item=>item.scope==='bank');
const average=bankAttempts.length?Math.round(bankAttempts.reduce((sum,item)=>sum+item.score,0)/bankAttempts.length):0;
const improved=attempts.filter((item,index)=>index>0&&item.scope==='bank'&&attempts.slice(0,index).some(old=>old.scope===item.scope&&old.id===item.id&&item.score>old.score)).length;
document.getElementById('teacherStats').innerHTML=`<article><span>התקדמות ביחידה</span><b>${Math.round(completed.length/10*100)}%</b><small>${completed.length} מתוך 10 דפים הושלמו</small></article><article><span>סעיפי בגרות שעברו</span><b>${passedParts.size}/27</b><small>${bankAttempts.length} סעיפים נבדקו לפחות פעם אחת</small></article><article><span>ממוצע רכיבי תשובה</span><b>${average}%</b><small>לפי הניסיון האחרון בכל סעיף</small></article><article><span>שיפורים לאחר משוב</span><b>${improved}</b><small>ניסיונות שבהם הציון עלה</small></article>`;
const missing=bankAttempts.flatMap(item=>item.missing),counts=missing.reduce((all,label)=>(all[label]=(all[label]||0)+1,all),{}),difficulties=Object.entries(counts).sort((a,b)=>b[1]-a[1]);
document.getElementById('difficultyList').innerHTML=difficulties.length?difficulties.slice(0,6).map(([label,count],index)=>`<div><i>${index+1}</i><span><b>${label}</b><small>חסר ב־${count} תשובות אחרונות</small></span><em style="--difficulty:${Math.min(100,count/Math.max(1,bankAttempts.length)*100)}%"></em></div>`).join(''):'<p class="empty-state">עדיין אין מספיק תשובות שנבדקו כדי לזהות דפוס.</p>';
const topDifficulty=difficulties[0]?.[0];document.getElementById('teacherAction').innerHTML=topDifficulty?`<span class="action-number">01</span><h3>לחזור בקצרה על: ${topDifficulty}</h3><p>פתחו את השיעור בדוגמה מלאה, בקשו מהתלמידים לסמן את רכיבי התשובה, ואז אפשרו ניסיון חוזר בשאלה המתאימה.</p><a class="button button-primary" href="units/coastal-plain.html#open-practice">פתיחת תרגול ממוקד</a>`:`<span class="action-number">01</span><h3>לאסוף ניסיון ראשון</h3><p>בקשו מהתלמידים לענות על סעיף אחד לפחות. לאחר הבדיקה תופיע כאן המלצה המבוססת על הקושי החוזר.</p><a class="button button-primary" href="units/coastal-plain.html#open-practice">פתיחת מאגר השאלות</a>`;
document.getElementById('questionPerformance').innerHTML=questionNames.map((name,i)=>{const parts=[0,1,2].map(p=>`${i}-${p}`),passed=parts.filter(key=>passedParts.has(key)).length,questionAttempts=bankAttempts.filter(item=>item.id.startsWith(`${i}-`)),score=questionAttempts.length?Math.round(questionAttempts.reduce((sum,item)=>sum+item.score,0)/questionAttempts.length):0;return`<div><span><b>שאלה ${i+1}</b><small>${name}</small></span><div class="part-dots">${parts.map((key,p)=>`<i class="${passedParts.has(key)?'done':''}" title="סעיף ${String.fromCharCode(1488+p)}">${String.fromCharCode(1488+p)}</i>`).join('')}</div><strong>${passed}/3</strong><em>${questionAttempts.length?score+'%':'טרם נבדק'}</em></div>`}).join('');

