const steps=['overview','north','carmel','telaviv','south','games','images','presentation','practice','open-practice'];
const completed=new Set(JSON.parse(localStorage.getItem('coastal-demo-progress')||'[]'));
function renderProgress(){const value=Math.round(completed.size/steps.length*100);document.getElementById('unitMeter').style.width=`${value}%`;document.getElementById('unitPercent').textContent=`${value}%`;document.querySelectorAll('.lesson-nav a').forEach(a=>a.classList.toggle('completed',completed.has(a.dataset.step)));document.querySelectorAll('[data-complete]').forEach(b=>{const done=completed.has(b.dataset.complete);b.classList.toggle('is-complete',done);b.textContent=done?'החלק הושלם ✓':'סיימתי את החלק הזה'});}
function completeStep(step){completed.add(step);localStorage.setItem('coastal-demo-progress',JSON.stringify([...completed]));renderProgress();}
document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>completeStep(b.dataset.complete)));

const enrichment={
north:['עוד אתרים שחייבים להכיר בצפון',['מוזיאון אסירי המחתרות','בית הכלא הבריטי בעכו שבו נכלאו לוחמי אצ״ל ולח״י; במקום תא הגרדום וסיפור פריצת הכלא.'],['מנהרת הטמפלרים','מנהרה תת־קרקעית של המסדר הטמפלרי המחברת בין המצודה לנמל עכו.'],['בית לוחמי הגטאות','מוזיאון לשואה שהקימו ניצולים שלחמו בגטאות.'],['גן לאומי אכזיב','לגונות וברכות ים, שרידי כפר דייגים, חוף ושטחי קמפינג.'],['מבצר מונפורט','מבצר צלבני בנחל כזיב ובו שרידי מגדל וחומות.'],['מבצר יחיעם','שרידים צלבניים ועות׳מאניים וסיפור מלחמת העצמאות.']],
carmel:['מוקדי הביקור בקיסריה ובכרמל',['התיאטרון הרומי','כ־3,500 מקומות; נבנה בתקופת הורדוס ומשמש גם כיום למופעים.'],['האקוודוקט','אמת מים רומית באורך כ־20 ק״מ שהובילה מים מהכרמל לקיסריה.'],['ההיפודרום וארמון הורדוס','מתחם למרוצי סוסים ושרידי ארמון מפואר על קו הים.'],['בית אהרנסון','בית המשפחה ומרכז סיפורה של מחתרת ניל״י.'],['רמת הנדיב','גני זיכרון וקברי הברון רוטשילד ורעייתו.'],['דלית אל־כרמל ועוספיה','שוק, מטבח, מורשת ואירוח המציגים את התרבות הדרוזית.']],
telaviv:['תרבות, בילוי ומוזיאונים בתל אביב',['נמל תל אביב','נמל ששוקם והפך למתחם פנאי ותרבות.'],['שרונה','מושבה טמפלרית משנת 1871 ובה עשרות מבנים ששומרו.'],['שוק הכרמל ונחלת בנימין','שוק מזון מרכזי ולצדו מדרחוב ויריד אמנים.'],['פארק הירקון','הריאה הירוקה העירונית ובה אגם ומתקני פנאי.'],['מוזיאון אנו','מוזיאון אינטראקטיבי לסיפור העם היהודי והתפוצות.'],['מוזיאוני הפלמ״ח וההגנה','אתרי מורשת על המאבק להקמת המדינה.']],
south:['מה מזהים ומה מסבירים בבגרות',['השער הכנעני באשקלון','שער מקושת בן כ־3,500 שנה, מן הקדומים מסוגו בעולם.'],['ייחוד תל אשקלון','שילוב ארכאולוגיה, חוף ים וטיילת צוק.'],['מערות הפעמון','חללים גדולים שנחצבו בידי אדם בסלע הקירטון.'],['קולומבריום ומקוואות','מתקנים לגידול יונים ובריכות טבילה קדומות בבית גוברין.']]
};
const imageMap={
'מוזיאון אסירי המחתרות':'https://nisan1234-afk.github.io/jerusalem-tour/images/image91.png',
'בית לוחמי הגטאות':'https://nisan1234-afk.github.io/jerusalem-tour/images/image88.png',
'גן לאומי אכזיב':'https://nisan1234-afk.github.io/jerusalem-tour/images/image102.png',
'מבצר מונפורט':'https://nisan1234-afk.github.io/jerusalem-tour/images/image89.png',
'מבצר יחיעם':'https://nisan1234-afk.github.io/jerusalem-tour/images/image90.png',
'התיאטרון הרומי':'https://nisan1234-afk.github.io/jerusalem-tour/images/image60.png',
'האקוודוקט':'https://nisan1234-afk.github.io/jerusalem-tour/images/image58.png',
'בית אהרנסון':'https://nisan1234-afk.github.io/jerusalem-tour/images/image92.png',
'רמת הנדיב':'https://nisan1234-afk.github.io/jerusalem-tour/images/image94.png',
'נמל תל אביב':'https://nisan1234-afk.github.io/jerusalem-tour/images/image75.png',
'שרונה':'https://nisan1234-afk.github.io/jerusalem-tour/images/image69.png',
'שוק הכרמל ונחלת בנימין':'https://nisan1234-afk.github.io/jerusalem-tour/images/image66.png',
'פארק הירקון':'https://nisan1234-afk.github.io/jerusalem-tour/images/image73.png',
'מוזיאון אנו':'https://nisan1234-afk.github.io/jerusalem-tour/images/image84.png',
'מוזיאוני הפלמ״ח וההגנה':'https://nisan1234-afk.github.io/jerusalem-tour/images/image68.png',
'ייחוד תל אשקלון':'https://nisan1234-afk.github.io/jerusalem-tour/images/image104.png',
'מערות הפעמון':'https://nisan1234-afk.github.io/jerusalem-tour/images/image105.png'
};
Object.entries(enrichment).forEach(([id,g])=>{const s=document.getElementById(id),btn=s?.querySelector('.complete-button');if(!s||!btn)return;const w=document.createElement('div');w.className='expanded-material';w.innerHTML=`<h3>${g[0]}</h3><div class="detail-grid">${g.slice(1).map(c=>`<article>${imageMap[c[0]]?`<img src="${imageMap[c[0]]}" alt="${c[0]}" loading="lazy">`:''}<div><span>חומר חובה</span><h4>${c[0]}</h4><p>${c[1]}</p></div></article>`).join('')}</div>`;s.insertBefore(w,btn)});

const imageChallenge=[
['ראש הנקרה','https://nisan1234-afk.github.io/jerusalem-tour/images/image100.jpg'],
['הגנים הבהאיים בחיפה','https://nisan1234-afk.github.io/jerusalem-tour/images/image98.jpg'],
['אולמות האבירים בעכו','https://nisan1234-afk.github.io/jerusalem-tour/images/image87.png'],
['האקוודוקט בקיסריה','https://nisan1234-afk.github.io/jerusalem-tour/images/image58.png'],
['נמל יפו','https://nisan1234-afk.github.io/jerusalem-tour/images/image64.png'],
['שרונה','https://nisan1234-afk.github.io/jerusalem-tour/images/image69.png'],
['גן לאומי אשקלון','https://nisan1234-afk.github.io/jerusalem-tour/images/image104.png'],
['מערות בית גוברין','https://nisan1234-afk.github.io/jerusalem-tour/images/image105.png']
];
const presentationSection=document.getElementById('presentation');
const imageSection=document.createElement('section');
imageSection.className='learning-block tinted image-practice';
imageSection.id='images';
imageSection.dataset.trackStep='images';
imageSection.innerHTML=`<div class="block-heading"><span class="number">06</span><div><span class="eyebrow">זיהוי אתרים מתמונה</span><h2>רואים, מזהים ומסבירים</h2></div></div><p class="practice-intro">בחרו את שם האתר המופיע בתמונה. לאחר הזיהוי תקבלו גם את פרט המפתח שכדאי לזכור לבגרות.</p><div class="recognition-card"><img id="recognitionImage" alt=""><div><span class="quiz-kicker" id="recognitionCount"></span><h3>איזה אתר מופיע בתמונה?</h3><div class="answer-list" id="recognitionAnswers"></div><p class="quiz-feedback" id="recognitionFeedback"></p><button class="button button-primary" id="nextRecognition" disabled>לתמונה הבאה</button></div></div>`;
presentationSection.parentNode.insertBefore(imageSection,presentationSection);
const presentationNav=document.querySelector('[data-step="presentation"]');
const imageNav=document.createElement('a');
imageNav.href='#images';imageNav.dataset.step='images';
imageNav.innerHTML='<i>6</i><span>זיהוי מתמונה<small>אתגר חזותי</small></span><b>✓</b>';
presentationNav.parentNode.insertBefore(imageNav,presentationNav);
document.querySelectorAll('[data-step="presentation"] i,[data-step="practice"] i').forEach((n,i)=>n.textContent=String(i+7));
let recognitionIndex=0,recognitionCorrect=0;
function renderRecognition(){const item=imageChallenge[recognitionIndex];document.getElementById('recognitionImage').src=item[1];document.getElementById('recognitionImage').alt='אתר לזיהוי';document.getElementById('recognitionCount').textContent=`תמונה ${recognitionIndex+1} מתוך ${imageChallenge.length}`;const wrong=imageChallenge.filter(x=>x[0]!==item[0]).sort(()=>.5-Math.random()).slice(0,2).map(x=>x[0]);const choices=[item[0],...wrong].sort(()=>.5-Math.random());const box=document.getElementById('recognitionAnswers');box.innerHTML='';choices.forEach(name=>{const b=document.createElement('button');b.textContent=name;b.addEventListener('click',()=>{box.querySelectorAll('button').forEach(x=>{x.disabled=true;if(x.textContent===item[0])x.classList.add('correct')});if(name===item[0])recognitionCorrect++;else b.classList.add('wrong');document.getElementById('recognitionFeedback').textContent=name===item[0]?'נכון — זהו '+item[0]+'.':'כמעט. התשובה הנכונה היא '+item[0]+'.';document.getElementById('nextRecognition').disabled=false});box.appendChild(b)});document.getElementById('recognitionFeedback').textContent='';document.getElementById('nextRecognition').disabled=true;}
document.getElementById('nextRecognition').addEventListener('click',()=>{if(recognitionIndex<imageChallenge.length-1){recognitionIndex++;renderRecognition();return}completeStep('images');document.querySelector('.recognition-card>div').innerHTML=`<span class="eyebrow">האתגר הושלם</span><h3>זיהית ${recognitionCorrect} מתוך ${imageChallenge.length} אתרים</h3><p>אפשר לחזור ליחידה בכל עת ולתרגל שוב.</p>`});renderRecognition();

const deepReads={
overview:['למה רוב האוכלוסייה כאן?','המישור הרחב, הקרבה לים, אפשרויות הבנייה והחקלאות וצירי התחבורה המרכזיים סייעו להתפתחות רצף עירוני גדול. לכן מרבית תושבי ישראל מתגוררים במישור החוף.','מה חייבים לכתוב בתשובה?','בתיאור נוף משלבים לפחות שלושה רכיבים: תבליט מישורי, קו חוף ישר וחולי בדרום, ורוחב ההולך וגדל מצפון לדרום.'],
north:['מה מושך תיירים לצפון?','האזור מאפשר לבנות מסלול מגוון: תופעת טבע בראש הנקרה, עיר היסטורית בעכו, אתרים דתיים בחיפה ושמורות ומבצרים בגליל המערבי.','תיירות דתית בחיפה','מערת אליהו מושכת בני ארבע דתות, סטלה מאריס מושך צליינים נוצרים, והגנים הבהאיים מושכים מאמינים ותיירים כלליים.'],
carmel:['קיסריה כמוצר תיירותי','ייחודה של קיסריה אינו רק בעתיקות. התיאטרון עדיין משמש למופעים והאקוודוקט ניצב על חוף פעיל — חיבור בין מורשת, תרבות ונופש.','מושבות העלייה הראשונה','זכרון יעקב משמרת את בית אהרנסון, רחובות המושבה ויקבים. אלה הופכים סיפור התיישבותי למוקדי ביקור חיים.'],
telaviv:['למה תל אביב מושכת תיירים?','חופי ים, חיי לילה, שווקים, אדריכלות, מוזיאונים, קולינריה ואירועים יוצרים מוצר עירוני מגוון המתאים לקהלים שונים.','יפו ותל אביב — ניגוד משלים','יפו מציעה נמל עתיק, שוק ומורשת; תל אביב מציעה עיר מודרנית, תרבות והעיר הלבנה. יחד נוצר מסלול המחבר עבר והווה.'],
south:['אשקלון לעומת נתניה','שתיהן מציעות חוף, מלונות וקניות. אשקלון מוסיפה פארק ארכאולוגי ושער כנעני, ואילו נתניה מזוהה יותר עם תיירות חוף ועם מסורת ליטוש היהלומים.','בית גוברין בשפלת יהודה','האתר נמצא באזור המעבר בין מישור החוף להר. הקירטון הרך איפשר חציבת מערות ששימשו למחצבות, גידול יונים, קבורה וטהרה.']
};
Object.entries(deepReads).forEach(([id,d])=>{const section=document.getElementById(id),button=section?.querySelector('.complete-button');if(!section||!button)return;const read=document.createElement('div');read.className='deep-read';read.innerHTML=`<article><span>להבין את התמונה</span><h3>${d[0]}</h3><p>${d[1]}</p></article><article><span>לבגרות</span><h3>${d[2]}</h3><p>${d[3]}</p></article>`;section.insertBefore(read,button)});

const gameSection=document.createElement('section');gameSection.className='learning-block learning-games';gameSection.id='games';gameSection.dataset.trackStep='games';
gameSection.innerHTML=`<div class="block-heading"><span class="number">06</span><div><span class="eyebrow">משחקי למידה</span><h2>שלושה אתגרים קצרים</h2></div></div><p class="practice-intro">כל משחק מתרגל מיומנות אחרת. אפשר לשחק שוב ללא הגבלה; השלב יושלם לאחר הצלחה בשלושת האתגרים.</p><div class="game-status"><b id="gamesCompleted">0 מתוך 3 משחקים הושלמו</b><div class="meter"><i id="gamesMeter"></i></div></div><div class="games-grid">
<article class="learning-game" data-game-card="regions"><span>משחק 1</span><h3>איפה נמצא האתר?</h3><p>התאימו כל אתר לאזור הנכון.</p><div id="regionGame"></div><button class="button button-outline" id="checkRegions">בדיקה</button><small id="regionFeedback"></small></article>
<article class="learning-game" data-game-card="clues"><span>משחק 2</span><h3>מי אני?</h3><p id="clueText"></p><div class="game-choices" id="clueChoices"></div><small id="clueFeedback"></small><button class="button button-outline" id="nextClue" disabled>הרמז הבא</button></article>
<article class="learning-game" data-game-card="route"><span>משחק 3</span><h3>מסלול מצפון לדרום</h3><p>סדרו את התחנות לפי כיוון הנסיעה.</p><div class="route-selects"><select id="route1"></select><select id="route2"></select><select id="route3"></select></div><button class="button button-outline" id="checkRoute">בדיקת המסלול</button><small id="routeFeedback"></small></article>
</div>`;imageSection.parentNode.insertBefore(gameSection,imageSection);
const gameNav=document.createElement('a');gameNav.href='#games';gameNav.dataset.step='games';gameNav.innerHTML='<i>6</i><span>משחקי למידה<small>שלושה אתגרים</small></span><b>✓</b>';imageNav.parentNode.insertBefore(gameNav,imageNav);document.querySelectorAll('[data-step="images"] i,[data-step="presentation"] i,[data-step="practice"] i').forEach((n,i)=>n.textContent=String(i+7));
const gameDone=new Set(JSON.parse(localStorage.getItem('coastal-games-done')||'[]'));function renderGamesProgress(){document.querySelectorAll('[data-game-card]').forEach(c=>c.classList.toggle('game-complete',gameDone.has(c.dataset.gameCard)));document.getElementById('gamesCompleted').textContent=`${gameDone.size} מתוך 3 משחקים הושלמו`;document.getElementById('gamesMeter').style.width=`${Math.round(gameDone.size/3*100)}%`;localStorage.setItem('coastal-games-done',JSON.stringify([...gameDone]));if(gameDone.size===3)completeStep('games')}
const regionItems=[['ראש הנקרה','צפון'],['עכו','צפון'],['קיסריה','כרמל'],['זכרון יעקב','כרמל'],['יפו','מרכז'],['בית גוברין','דרום']];document.getElementById('regionGame').innerHTML=regionItems.map((x,i)=>`<label><b>${x[0]}</b><select data-region="${i}"><option value="">בחרו אזור</option><option>צפון</option><option>כרמל</option><option>מרכז</option><option>דרום</option></select></label>`).join('');document.getElementById('checkRegions').addEventListener('click',()=>{const correct=regionItems.filter((x,i)=>document.querySelector(`[data-region="${i}"]`).value===x[1]).length;document.getElementById('regionFeedback').textContent=`${correct} מתוך ${regionItems.length} התאמות נכונות`;if(correct===regionItems.length){gameDone.add('regions');renderGamesProgress()}});
const clueItems=[['יש בי 19 טרסות וכיפת זהב',['הגנים הבהאיים','רמת הנדיב','סטלה מאריס'],0],['אני אמת מים רומית באורך כ־20 ק״מ',['האקוודוקט','מנהרת הטמפלרים','נמל יפו'],0],['מכנים אותי ארץ אלף המערות',['בית גוברין','ראש הנקרה','קיסריה'],0],['אני שכונה יהודית שנוסדה בשנת 1887',['נווה צדק','שרונה','עוספיה'],0],['אצלי נמצא שער כנעני מקושת בן כ־3,500 שנה',['תל אשקלון','עכו','מונפורט'],0]];let clueIndex=0,clueScore=0;function renderClue(){const c=clueItems[clueIndex];document.getElementById('clueText').textContent=c[0];document.getElementById('clueFeedback').textContent=`רמז ${clueIndex+1} מתוך ${clueItems.length}`;document.getElementById('clueChoices').innerHTML='';[...c[1]].sort(()=>.5-Math.random()).forEach(name=>{const b=document.createElement('button');b.textContent=name;b.addEventListener('click',()=>{document.querySelectorAll('#clueChoices button').forEach(x=>x.disabled=true);if(name===c[1][c[2]]){b.classList.add('correct');clueScore++}else{b.classList.add('wrong');[...document.querySelectorAll('#clueChoices button')].find(x=>x.textContent===c[1][c[2]])?.classList.add('correct')}document.getElementById('nextClue').disabled=false});document.getElementById('clueChoices').appendChild(b)})}document.getElementById('nextClue').addEventListener('click',()=>{if(clueIndex<clueItems.length-1){clueIndex++;document.getElementById('nextClue').disabled=true;renderClue();return}document.getElementById('clueFeedback').textContent=`סיימתם עם ${clueScore} מתוך ${clueItems.length}`;if(clueScore>=4){gameDone.add('clues');renderGamesProgress()}else{clueIndex=0;clueScore=0;document.getElementById('nextClue').disabled=true;renderClue()}});renderClue();
const routeStops=['בחרו תחנה','ראש הנקרה','עכו','חיפה'];['route1','route2','route3'].forEach(id=>document.getElementById(id).innerHTML=routeStops.map(x=>`<option>${x}</option>`).join(''));document.getElementById('checkRoute').addEventListener('click',()=>{const route=['route1','route2','route3'].map(id=>document.getElementById(id).value),ok=route.join('|')==='ראש הנקרה|עכו|חיפה';document.getElementById('routeFeedback').textContent=ok?'מסלול נכון: מצפון לדרום ✓':'בדקו שוב את המיקום הגיאוגרפי של התחנות.';if(ok){gameDone.add('route');renderGamesProgress()}});renderGamesProgress();

const slides=[
['מישור החוף','חזרה לבגרות','מסע מראש הנקרה ועד הדרום: גיאוגרפיה, ארכאולוגיה, תרבות וטבע.','מתחילים מצפון'],
['גיאוגרפיה ונוף','ראש הנקרה עד עזה','רצועה מישורית לאורך הים התיכון, באורך כ־190 ק״מ.','מפת היחידה'],
['גיאוגרפיה','מישור החוף במספרים','רוחב 4 ק״מ בצפון ועד 40 ק״מ בדרום; נקטע בראש הנקרה ובכרמל.','שאלה 6א'],
['גיאוגרפיה','חוף צבירה וחוף סחיפה','בדרום חוף רחב, ישר וחולי; בצפון מפרצונים ולוחות גידוד.','השוואה חשובה'],
['החוף הצפוני','ראש הנקרה','גלי הים יצרו נקרות בסלע הגיר; באתר רכבל ומיצג אור־קולי.','שאלה 6ב'],
['עכו','עיר מורשת עולמית','שכבה צלבנית תת־קרקעית ושכבה עות׳מאנית מעל הקרקע.','UNESCO'],
['עכו','אולמות, מסגד וחאן','אולמות האבירים, מסגד אל־ג׳זאר וחאן אל־עומדאן.','שאלות 7א ו־9ב'],
['עכו','מורשת ומחתרות','מוזיאון אסירי המחתרות, מנהרת הטמפלרים ובית לוחמי הגטאות.','העבר ממשיך לדבר'],
['חיפה','הגנים הבהאיים','19 טרסות, מקדש הבב וכיפת הזהב; מרכז הדת הבהאית.','UNESCO 2008'],
['חיפה','מערת אליהו וסטלה מאריס','המערה קדושה לארבע דתות; מעליה מרכז המסדר הכרמליתי.','קדושה וצליינות'],
['טבע ומבצרים','אכזיב, מונפורט ויחיעם','לגונות וחוף, מבצר צלבני וסיפור מלחמת העצמאות.','שלושה סוגי ביקור'],
['בדיקת ידע','עכו: ארכאולוגיה וקדושה','אולמות האבירים כאתר ארכאולוגי ומסגד אל־ג׳זאר כאתר קדוש.','מבנה תשובה'],
['קיסריה והכרמל','עיר הורדוס','עיר נמל מפוארת בת כ־2,000 שנה.','עוברים למרכז'],
['קיסריה','מוקדי הביקור','תיאטרון, היפודרום, רחוב צלבני וארמון הורדוס.','ארכאולוגיה חיה'],
['קיסריה','האקוודוקט','אמת מים רומית באורך כ־20 ק״מ שנשמרה לצד החוף.','שאלה 8ב'],
['זכרון יעקב','מושבה, ניל״י ויין','מושבה מ־1882: בית אהרנסון, דרך היין ורמת הנדיב.','שאלות 8ג ו־9א'],
['הכרמל','הכפרים הדרוזיים','דלית אל־כרמל ועוספיה: שוק, מטבח, מורשת ואירוח.','תיירות תרבותית'],
['בדיקת ידע','שני אתרים בקיסריה','התיאטרון והאקוודוקט: בכל תשובה משלבים עובדה והסבר.','תשובת בגרות'],
['תל אביב–יפו','יפו העתיקה','נמל דייגים, סלע אנדרומדה, מגדל השעון ושוק הפשפשים.','ישן וחדש'],
['תל אביב','נווה צדק והעיר הלבנה','נווה צדק מ־1887 ויותר מ־4,000 מבנים בסגנון הבינלאומי.','UNESCO 2003'],
['תל אביב','אתרים ובילוי','הנמל, שרונה, שוק הכרמל, פארק הירקון ונחלת בנימין.','עיר מגוונת'],
['תל אביב','מוזיאונים','אנו, ארץ ישראל, הפלמ״ח וההגנה.','תרבות ומורשת'],
['בדיקת ידע','ייחוד העיר הלבנה','ריכוז מבני הסגנון הבינלאומי ותכנון עיר גנים.','תשובה מלאה'],
['החוף הדרומי','גן לאומי תל אשקלון','שער כנעני ושילוב של ארכאולוגיה, חוף וטיילת.','שאלות 1ב ו־1ג'],
['בית גוברין','ארץ אלף המערות','מערות פעמון, קולומבריום, קברים ומקוואות.','UNESCO'],
['בדיקת ידע','ייחוד בית גוברין','מערכות חציבה מעשה אדם ושימושים מגוונים.','שאלה 5א'],
['תכנון מסלול','יומיים מנהרייה','ראש הנקרה ועכו; למחרת מונפורט, יחיעם ואכזיב.','שאלה 9ג'],
['סיכום','מצפון עד דרום','מזהים אתר, משייכים לאזור ומנסחים עובדה והסבר.','מוכנים לתרגול']
].map(([section,title,body,accent])=>({section,title,body,accent}));
let slideIndex=0;const stage=document.getElementById('slideStage');
function renderSlide(){const s=slides[slideIndex];stage.innerHTML=`<div class="web-slide"><span>${s.section}</span><h3>${s.title}</h3><p>${s.body}</p><b>${s.accent}</b></div>`;document.getElementById('slideCounter').textContent=`${slideIndex+1} / ${slides.length}`;document.getElementById('prevSlide').disabled=slideIndex===0;document.getElementById('nextSlide').disabled=slideIndex===slides.length-1;if(slideIndex===slides.length-1){const f=document.getElementById('completeSlides');f.disabled=false;f.textContent='סיימתי את המצגת';}}
document.getElementById('nextSlide').addEventListener('click',()=>{if(slideIndex<slides.length-1){slideIndex++;renderSlide()}});document.getElementById('prevSlide').addEventListener('click',()=>{if(slideIndex>0){slideIndex--;renderSlide()}});document.getElementById('fullScreenSlide').addEventListener('click',()=>document.getElementById('slidePlayer').requestFullscreen?.());document.getElementById('completeSlides').addEventListener('click',()=>completeStep('presentation'));

const questions=[
['מה מאפיין חוף צבירה?',['חוף רחב, ישר וחולי','מצוק גיר ובו נקרות','לוחות גידוד בלבד'],0,'חוף צבירה אופייני לדרום והוא רחב, ישר וחולי.'],
['כיצד נוצרו הנקרות בראש הנקרה?',['מפעולת גלי הים בסלע הגיר','מחציבה רומית','מרעידת אדמה'],0,'הגלים פעלו לאורך זמן בסלע הגיר.'],
['איזה אתר בעכו הוא צלבני?',['אולמות האבירים','מסגד אל־ג׳זאר','מגדל השעון'],0,'אולמות האבירים הם מתחם צלבני תת־קרקעי.'],
['כמה טרסות יש בגנים הבהאיים?',['19','12','40'],0,'בגנים הבהאיים 19 טרסות.'],
['מה היה תפקיד האקוודוקט?',['הובלת מים לקיסריה','הגנה על הנמל','מרוצי סוסים'],0,'האקוודוקט הוביל מים מהכרמל לקיסריה.'],
['איזה סיפור מוצג בבית אהרנסון?',['מחתרת ניל״י','המסדר הכרמליתי','הקמת הפלמ״ח'],0,'הבית מספר את סיפורה של מחתרת ניל״י.'],
['מה מייחד את העיר הלבנה?',['מבנים בסגנון הבינלאומי ועיר גנים','נמל עתיק','מגדל שעון'],0,'זהו ריכוז גדול של מבני הסגנון הבינלאומי.'],
['איזה מוזיאון מספר את סיפור התפוצות?',['אנו','הפלמ״ח','בית אהרנסון'],0,'מוזיאון אנו עוסק בעם היהודי ובתפוצות.'],
['מה מייחד את תל אשקלון?',['ארכאולוגיה, חוף וטיילת','19 טרסות','אמת מים'],0,'באתר יש שילוב ייחודי של ארכאולוגיה וחוף.'],
['מה מכונה ארץ אלף המערות?',['בית גוברין','תל אשקלון','קיסריה'],0,'בית גוברין מוכר במערות הפעמון ובמערכות החציבה.']
].map(([q,a,correct,explain])=>({q,a,correct,explain}));
let questionIndex=0,correctAnswers=0;
function renderQuestion(){const x=questions[questionIndex];document.querySelector('#quizCard .quiz-kicker').textContent=`שאלה ${questionIndex+1} מתוך ${questions.length}`;document.getElementById('questionText').textContent=x.q;const l=document.getElementById('answerList');l.innerHTML='';x.a.forEach((a,i)=>{const b=document.createElement('button');b.textContent=a;b.addEventListener('click',()=>checkAnswer(i,b));l.appendChild(b)});document.getElementById('quizFeedback').textContent='';const n=document.getElementById('nextQuestion');n.disabled=true;n.textContent=questionIndex===questions.length-1?'לסיום ולקבלת ציון':'לשאלה הבאה';}
function checkAnswer(i,b){const x=questions[questionIndex],buttons=document.querySelectorAll('#answerList button');buttons.forEach(c=>c.disabled=true);b.classList.add(i===x.correct?'correct':'wrong');if(i!==x.correct)buttons[x.correct].classList.add('correct');if(i===x.correct)correctAnswers++;document.getElementById('quizFeedback').textContent=x.explain;document.getElementById('nextQuestion').disabled=false;}
document.getElementById('nextQuestion').addEventListener('click',()=>{if(questionIndex<questions.length-1){questionIndex++;renderQuestion();return}const score=Math.round(correctAnswers/questions.length*100);document.getElementById('quizCard').innerHTML=`<span class="eyebrow">התרגול הסתיים</span><h3>הציון שלך: ${score}</h3><p>${score>=60?'עברת את שלב התרגול. כל הכבוד.':'כדאי לחזור על החומר ולנסות שוב. מספר הניסיונות אינו מוגבל.'}</p><button class="button button-outline" onclick="location.reload()">ניסיון נוסף</button>`;localStorage.setItem('coastal-demo-last-score',String(score));if(score>=60)completeStep('practice')});
const openPracticeData=[
{title:'נוף ותיירות בדרום',topic:'גיאוגרפיה · אשקלון · נתניה',question:'א. תארו את הנוף האופייני למישור החוף המרכזי והדרומי. ב. ציינו שני אתרי תיירות מיוחדים בשפלת החוף והסבירו מה מייחד אותם. ג. ציינו אילו סוגי תיירות לשם הנאה מוצעים באשקלון ובנתניה, והסבירו מה מייחד את אשקלון לעומת נתניה.',model:'הנוף מישורי, קו החוף ישר וארוך והחוף רחב וחולי. תל אשקלון מיוחד בשער הכנעני ובשילוב ארכאולוגיה וחוף; בית גוברין מיוחד במערותיו. נתניה מציעה חוף, מלונות וקניות; אשקלון מוסיפה ארכאולוגיה וטיילת צוק.'},
{title:'יפו והעיר הלבנה',topic:'תל אביב–יפו · UNESCO',question:'א. ציינו שני מוקדי תיירות מעניינים ביפו וכתבו מה מייחד כל אחד. ב. ציינו שכונה היסטורית שנוסדה מחוץ ליפו לפני תל אביב ותארו אותה. ג. הסבירו את ייחוד העיר הלבנה שזיכה אותה בהכרה של UNESCO.',model:'נמל יפו משלב נמל דייגים, היסטוריה ואווירה ים־תיכונית; שוק הפשפשים מציע יד שנייה וחוויה עממית. נווה צדק נוסדה ב־1887 ובה בתים, גלריות ומסעדות. העיר הלבנה כוללת יותר מ־4,000 מבנים בסגנון הבינלאומי ותכנון עיר גנים.'},
{title:'ארכאולוגיה, בהאים ותל אביב',topic:'שרידים · דת · עירוניות',question:'א. ציינו שתי ערים במישור החוף המרכזי והדרומי שנמצאו בהן שרידים ארכאולוגיים; בחרו אחת ותארו שריד המושך תיירים. ב. הסבירו מיהם הבהאים וציינו שני אתרים קדושים להם בישראל. ג. ציינו שלושה מגורמי המשיכה של תל אביב לתיירים.',model:'בקיסריה ובאשקלון נמצאו שרידים; לדוגמה, השער הכנעני המקושת באשקלון. הבהאים הם בני דת שנוסדה בפרס ומקדשת את אחדות האנושות; אתריהם הקדושים הם מקדש הבב בחיפה ובהג׳י בעכו. תל אביב מושכת בזכות חופים, תרבות וחיי לילה.'},
{title:'מוזיאונים והכפרים הדרוזיים',topic:'תרבות · גליל מערבי · כרמל',question:'א. בחרו שני מוזיאונים בתל אביב ותארו מה מייחד כל אחד. ב. ציינו שני מוזיאונים במישור החוף הצפוני ותארו מה ניתן לראות בהם. ג. ציינו את שני הכפרים הדרוזיים בכרמל ושלוש פעילויות תיירותיות המתקיימות בהם.',model:'בתל אביב אפשר לבחור במוזיאון אנו ובמוזיאון הפלמ״ח. בצפון אפשר לבחור במוזיאון אסירי המחתרות ובבית לוחמי הגטאות. הכפרים הם דלית אל־כרמל ועוספיה; הפעילויות כוללות שוק, אוכל דרוזי, בית מורשת ואירוח ביתי.'},
{title:'בית גוברין ומוקדי משיכה',topic:'שפלת יהודה · תל אביב · הצפון',question:'א. תארו מה ניתן לראות באתר בית גוברין. ב. ציינו שני אתרי תיירות בתל אביב–יפו ותארו אותם. ג. ציינו שלושה גורמי משיכה תיירותיים במישור החוף הצפוני והביאו דוגמה לכל אחד.',model:'בבית גוברין מערות פעמון, קולומבריום, קברים ומקוואות. בתל אביב–יפו אפשר לתאר את נמל יפו ושרונה. בצפון גורמי המשיכה כוללים טבע — ראש הנקרה; ארכאולוגיה — עכו; ודת — הגנים הבהאיים או סטלה מאריס.'},
{title:'גבולות, ראש הנקרה וחיפה',topic:'החוף הצפוני · תשתיות · מגזרי תיירות',question:'א. מהם הגבולות הגיאוגרפיים של מישור החוף הצפוני? ב. תארו מה ניתן לראות בראש הנקרה וציינו את התשתיות התיירותיות באתר. ג. ציינו שני אתרי תיירות בחיפה ואיזה מגזר תיירותי ייכלל בתכנית הביקור בכל אחד.',model:'האזור משתרע מראש הנקרה עד הכרמל. בראש הנקרה רואים מצוק ונקרות שנוצרו בגלים; במקום רכבל, מיצג, רכבת תיירותית, חניון ומסעדה. הגנים הבהאיים מתאימים לתיירות בהאית וכללית; סטלה מאריס לתיירות צליינית נוצרית.'},
{title:'עכו, טבע ודת בחיפה',topic:'ארכאולוגיה · שמורות · דתות',question:'א. תארו שני אתרי תיירות בעכו — אחד ארכאולוגי ואחד קדוש. ב. ציינו פארק או שמורת טבע בחוף הגליל המערבי ותארו מה מושך אליו מבקרים. ג. ציינו שני אתרים בחיפה החשובים לבני דתות שונות והסבירו את חשיבותם ואת תרומתם לתיירות.',model:'אולמות האבירים הם מתחם צלבני תת־קרקעי; מסגד אל־ג׳זאר קדוש למוסלמים. אכזיב מושך בזכות לגונות, חוף וקמפינג. מערת אליהו קדושה לארבע דתות והגנים הבהאיים הם מרכז עולמי לבהאים — שניהם מושכים מאמינים ותיירים.'},
{title:'חיפה, קיסריה ומושבות',topic:'מוזיאונים · עתיקות · עלייה ראשונה',question:'א. בחרו שני מוזיאונים בחיפה ותארו מה מייחד כל אחד. ב. ציינו שני אתרים בולטים בקיסריה וספרו עליהם. ג. ציינו שתי מושבות עלייה ראשונה בשולי הכרמל ומוקד משיכה אחד בכל אחת.',model:'בחיפה אפשר לבחור במוזיאון הימי הלאומי ובמוזיאון חיפה לאמנות. בקיסריה התיאטרון הרומי משמש למופעים והאקוודוקט הוביל מים לאורך כ־20 ק״מ. בזכרון יעקב מוקד משיכה הוא בית אהרנסון; בבנימינה — אתרי מורשת ויקבים.'},
{title:'זכרון יעקב וסיור מנהרייה',topic:'שימור · צלבנים · תכנון מסלול',question:'א. ציינו שני אתרים בזכרון יעקב המשמרים את עברה ההיסטורי. ב. ציינו שני אתרים במישור החוף הצפוני שהם שרידים מתקופת הצלבנים. ג. תכננו סיור בן יומיים היוצא מנהרייה וכולל שישה אתרים — שלושה בכל יום; ציינו סוג אתר ומשך שהייה.',model:'בזכרון יעקב: בית אהרנסון ודרך היין או רחוב המייסדים. שרידים צלבניים: אולמות האבירים והמונפורט. יום א׳: ראש הנקרה — טבע, 90 דקות; אולמות האבירים — ארכאולוגיה, שעתיים; מסגד אל־ג׳זאר — דת, 45 דקות. יום ב׳: מונפורט — היסטוריה וטבע, שעתיים; יחיעם — היסטוריה, 90 דקות; אכזיב — טבע ונופש, שעה.'}
];
const practiceSection=document.getElementById('practice');const openSection=document.createElement('section');openSection.className='learning-block open-practice';openSection.id='open-practice';openSection.dataset.trackStep='open-practice';
openSection.innerHTML=`<div class="block-heading"><span class="number">09</span><div><span class="eyebrow">שאלות בגרות מחומרי המקור</span><h2>מאגר שאלות מישור החוף</h2></div></div><p class="practice-intro">תשע שאלות מתוך הקובץ המקורי שבתיקיית חומרי הגלם. לא צוינה בקובץ שנת בחינה, ולכן הן אינן מתויגות לפי שנה. הטיוטות נשמרות במכשיר הזה.</p><div class="bank-progress"><b id="bankCompleted">0 מתוך 9 הושלמו</b><div class="meter"><i id="bankMeter"></i></div></div><div class="open-question-list">${openPracticeData.map((q,i)=>`<article class="open-question" data-open-card="${i}"><div class="question-label"><span>שאלה ${i+1}</span><em>${q.topic}</em></div><h3>${q.title}</h3><p>${q.question}</p><textarea data-open-answer="${i}" rows="8" placeholder="כתבו כאן תשובה מלאה לכל הסעיפים..."></textarea><div class="answer-meta"><small data-word-count="${i}">0 מילים</small><small data-answer-state="${i}">טרם הושלם</small></div><details><summary>מחוון ותשובת דוגמה</summary><div><b>בדיקה עצמית:</b><ul><li>עניתי על כל סעיפי השאלה</li><li>ציינתי שמות מדויקים של אתרים</li><li>לכל אתר הוספתי עובדה והסבר</li></ul><p>${q.model}</p></div></details></article>`).join('')}</div><div class="open-actions"><button class="button button-primary" id="saveOpenPractice">שמירת כל הטיוטות</button><p id="openPracticeFeedback" class="quiz-feedback"></p></div>`;
practiceSection.parentNode.insertBefore(openSection,practiceSection.nextSibling);const practiceNav=document.querySelector('[data-step="practice"]');const openNav=document.createElement('a');openNav.href='#open-practice';openNav.dataset.step='open-practice';openNav.innerHTML='<i>10</i><span>מאגר בגרות<small>כתיבה פתוחה</small></span><b>✓</b>';practiceNav.parentNode.appendChild(openNav);
const openDrafts=JSON.parse(localStorage.getItem('coastal-open-drafts')||'{}');function updateBankProgress(){const answers=[...document.querySelectorAll('[data-open-answer]')];let done=0;answers.forEach(t=>{const i=t.dataset.openAnswer,words=t.value.trim()?t.value.trim().split(/\s+/).length:0,isDone=words>=25;document.querySelector(`[data-word-count="${i}"]`).textContent=`${words} מילים`;document.querySelector(`[data-answer-state="${i}"]`).textContent=isDone?'מוכן לבדיקה ✓':'טרם הושלם';document.querySelector(`[data-open-card="${i}"]`).classList.toggle('answer-complete',isDone);if(isDone)done++});document.getElementById('bankCompleted').textContent=`${done} מתוך ${openPracticeData.length} הושלמו`;document.getElementById('bankMeter').style.width=`${Math.round(done/openPracticeData.length*100)}%`;return done}
document.querySelectorAll('[data-open-answer]').forEach(t=>{t.value=openDrafts[t.dataset.openAnswer]||'';t.addEventListener('input',updateBankProgress)});updateBankProgress();
document.getElementById('saveOpenPractice').addEventListener('click',()=>{const values=[...document.querySelectorAll('[data-open-answer]')].map(t=>t.value.trim()),saved={};values.forEach((v,i)=>saved[i]=v);localStorage.setItem('coastal-open-drafts',JSON.stringify(saved));const done=updateBankProgress(),ready=done===openPracticeData.length;document.getElementById('openPracticeFeedback').textContent=ready?'כל תשע הטיוטות נשמרו והשלב הושלם.':'הטיוטות נשמרו. השלמתם '+done+' מתוך '+openPracticeData.length+' שאלות.';if(ready)completeStep('open-practice')});
const rail=document.getElementById('lessonRail');document.getElementById('railButton').addEventListener('click',()=>rail.classList.toggle('open'));renderProgress();renderSlide();renderQuestion();

